services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222" # NATS Management Port
    command: ["-js"]
    networks:
      - nats-network-poc

  order-service:
    build:
      context: .
      dockerfile: Dockerfile.order
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      nats:
        condition: service_started
    networks:
      - nats-network-poc

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile.inventory
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      nats:
        condition: service_started
    networks:
      - nats-network-poc

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.notification
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      nats:
        condition: service_started
    networks:
      - nats-network-poc

networks:
  nats-network-poc:
    name: nats-network-poc