FROM golang:1.20-alpine
WORKDIR /app
COPY ./notification/go.mod ./notification/go.sum ./
RUN go mod download
COPY . .
RUN go build -o notification-service ./notification/main.go
CMD ["./notification-service"] 